version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: DockerFile.prod
    container_name: nest-backend-prod
    ports:
      - "5001:5001"
    env_file:
      - ./.production.env
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres-prod
    restart: always
    env_file:
      - ./.production.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata_prod:/var/lib/postgresql/data

volumes:
  pgdata_prod:
