version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: DockerFile.dev
    container_name: nest-backend-dev
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ./.development.env
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    command: npm run start:dev

  db:
    image: postgres:16
    container_name: postgres-dev
    restart: always
    env_file:
      - ./.development.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

volumes:
  pgdata_dev:
