
export const RabbitMqQueueEnv = {
  ASSETS_QUEUE: "ASSETS_QUEUE",
  WORKER_QUEUE: 'WORKER_QUEUE',
  IDENTITY_QUEUE: 'IDENTITY_QUEUE',
  PORTFOLIO_QUEUE: 'PORTFOLIO_QUEUE',
  INDEXES_QUEUE: 'INDEXES_QUEUE',
  STOCKS_QUEUE: 'STOCKS_QUEUE',
  
} as const;